apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-broker-rolebinding
  namespace: seonho-test
subjects:
- kind: ServiceAccount
  name: seonho-test
roleRef:
  kind: Role
  name: service-broker-role
  apiGroup: rbac.authorization.k8s.io
